version: '3'


services:
  mongo: 
    image: mongo:5.0.0
    container_name: despachate-database
    ports: 
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  mongo-seed:
    image: mongo:5.0.0
    links: 
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command: 
      /mongo-seed/import.sh